### ISSUE TITLE
Error when missing solarwinds user

### ISSUE THREAD

**Issue by xocasdashdash** [DrFaust92/terraform-provider-pingdom#14]
Hey!

We're hitting an issue where the provider fails with a "missing cookie" error when we start it. After some debugging it seems that the pingdomext client requires this values, even though they're marked as optional. 

Can this be made optional? I can open a PR if it's OK

**Comment by tbpoetke** [comment]
@xocasdashdash Is there a workaround until @DrFaust92 is merging the PR? I tried with empty strings, but this is not working.

**Comment by xocasdashdash** [comment]
I don't believe so, the PR just makes it safe to use if the value is empty
