### ISSUE TITLE
No data sources for users and teams

### ISSUE THREAD

**Issue by sviatlo** [DrFaust92/terraform-provider-pingdom#6]
There are no data source for users. 

Currently, we hardcode user ids in pingdom check resource like this:
```
resource "pingdom_check" "my_check" {
  ...

  userids = [
    1234567,
    8901234
  ]
}
```

It would be great if there was an option to discover users by email and reference userid from the data source attributes.

**Comment by DrFaust92** [comment]
supported, ill just write the docs
